### ISSUE TITLE
KeyError: 'userpictures/htdocs'

### ISSUE THREAD

**Issue by aensley** [trac-hacks/trac-UserPicturesPlugin#1]
I've just installed your plugin, and it seems to be working fine (using Gravatars). However, I am receiving the error `KeyError: 'userpictures/htdocs'` in my Trac log file on every page view.

I am using Trac 1.0.4 behind Apache2 + FastCGI. I downloaded the source of the plugin from [here](https://pypi.python.org/pypi/trac-UserPicturesPlugin/), ran `python setup.py bdist_egg` from the source directory, and moved it to my Trac installation's `plugins` directory. I do not have the UserManager plugin installed (as I don't need/want it).

Relevant portions of my `trac.ini` file:

```
[components]
userpictures.* = enabled

[userpictures]
pictures_provider = UserPicturesGravatarProvider
```

Here is the full stack trace:

```
Trac[main] ERROR: Internal Server Error: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/trac/web/main.py", line 513, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/local/lib/python2.7/dist-packages/trac/web/main.py", line 222, in dispatch
    resp = chosen_handler.process_request(req)
  File "/usr/local/lib/python2.7/dist-packages/trac/web/chrome.py", line 674, in process_request
    in provider.get_htdocs_dirs() or []
  File "build/bdist.linux-x86_64/egg/userpictures/__init__.py", line 68, in get_htdocs_dirs
    yield 'userpictures', resource_filename(__name__, 'htdocs')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1129, in resource_filename
    self, resource_name
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1826, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1847, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'userpictures/htdocs'
```

Sorry if this isn't the right place to raise an issue. I wasn't sure whether to do it here, bitbucket, or Trac-Hacks.org.

**Comment by rjollos** [comment]
Before the proposed change:

```
(pve)~/Documents/Workspace/th-dev/UserPicturesPlugin/temp2$unzip trac-UserPicturesPlugin-master.zip 
Archive:  trac-UserPicturesPlugin-master.zip
1687caec58018b7fa5914596f45d2b8048e5e9be
   creating: trac-UserPicturesPlugin-master/
  inflating: trac-UserPicturesPlugin-master/.gitignore  
  inflating: trac-UserPicturesPlugin-master/CHANGES.txt  
  inflating: trac-UserPicturesPlugin-master/LICENSE.txt  
  inflating: trac-UserPicturesPlugin-master/README.txt  
  inflating: trac-UserPicturesPlugin-master/setup.py  
   creating: trac-UserPicturesPlugin-master/userpictures/
  inflating: trac-UserPicturesPlugin-master/userpictures/__init__.py  
   creating: trac-UserPicturesPlugin-master/userpictures/htdocs/
 extracting: trac-UserPicturesPlugin-master/userpictures/htdocs/default-portrait.gif  
  inflating: trac-UserPicturesPlugin-master/userpictures/htdocs/userpictures.css  
   creating: trac-UserPicturesPlugin-master/userpictures/providers/
  inflating: trac-UserPicturesPlugin-master/userpictures/providers/__init__.py  
  inflating: trac-UserPicturesPlugin-master/userpictures/providers/gravatar.py  
  inflating: trac-UserPicturesPlugin-master/userpictures/providers/usermanager.py  
(pve)~/Documents/Workspace/th-dev/UserPicturesPlugin/temp2$cd trac-UserPicturesPlugin-master/
(pve)~/Documents/Workspace/th-dev/UserPicturesPlugin/temp2/trac-UserPicturesPlugin-master$python setup.py sdist
running sdist
running egg_info
creating trac_UserPicturesPlugin.egg-info
writing trac_UserPicturesPlugin.egg-info/PKG-INFO
writing top-level names to trac_UserPicturesPlugin.egg-info/top_level.txt
writing dependency_links to trac_UserPicturesPlugin.egg-info/dependency_links.txt
writing entry points to trac_UserPicturesPlugin.egg-info/entry_points.txt
writing manifest file 'trac_UserPicturesPlugin.egg-info/SOURCES.txt'
reading manifest file 'trac_UserPicturesPlugin.egg-info/SOURCES.txt'
writing manifest file 'trac_UserPicturesPlugin.egg-info/SOURCES.txt'
running check
creating trac-UserPicturesPlugin-0.1.1
creating trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
creating trac-UserPicturesPlugin-0.1.1/userpictures
creating trac-UserPicturesPlugin-0.1.1/userpictures/providers
making hard links in trac-UserPicturesPlugin-0.1.1...
hard linking README.txt -> trac-UserPicturesPlugin-0.1.1
hard linking setup.py -> trac-UserPicturesPlugin-0.1.1
hard linking trac_UserPicturesPlugin.egg-info/PKG-INFO -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/SOURCES.txt -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/dependency_links.txt -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/entry_points.txt -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/not-zip-safe -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/top_level.txt -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking userpictures/__init__.py -> trac-UserPicturesPlugin-0.1.1/userpictures
hard linking userpictures/providers/__init__.py -> trac-UserPicturesPlugin-0.1.1/userpictures/providers
hard linking userpictures/providers/gravatar.py -> trac-UserPicturesPlugin-0.1.1/userpictures/providers
hard linking userpictures/providers/usermanager.py -> trac-UserPicturesPlugin-0.1.1/userpictures/providers
Writing trac-UserPicturesPlugin-0.1.1/setup.cfg
creating dist
Creating tar archive
removing 'trac-UserPicturesPlugin-0.1.1' (and everything under it)
(pve)~/Documents/Workspace/th-dev/UserPicturesPlugin/temp2/trac-UserPicturesPlugin-master$tar tzvf dist/trac-UserPicturesPlugin-0.1.1.tar.gz 
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/
-rw-r--r--  0 rjollos staff    3682 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/PKG-INFO
-rw-r--r--  0 rjollos staff    2588 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/README.txt
-rw-r--r--  0 rjollos staff      59 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/setup.cfg
-rw-r--r--  0 rjollos staff     850 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/setup.py
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/
-rw-r--r--  0 rjollos staff       1 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/dependency_links.txt
-rw-r--r--  0 rjollos staff      62 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/entry_points.txt
-rw-r--r--  0 rjollos staff       1 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/not-zip-safe
-rw-r--r--  0 rjollos staff    3682 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/PKG-INFO
-rw-r--r--  0 rjollos staff     436 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/SOURCES.txt
-rw-r--r--  0 rjollos staff      13 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/top_level.txt
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/userpictures/
-rw-r--r--  0 rjollos staff   14170 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/__init__.py
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/userpictures/providers/
-rw-r--r--  0 rjollos staff     157 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/providers/__init__.py
-rw-r--r--  0 rjollos staff    1441 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/providers/gravatar.py
-rw-r--r--  0 rjollos staff     834 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/providers/usermanager.py
```

**Comment by rjollos** [comment]
After the proposed change

```
(pve)~/Documents/Workspace/th-dev/UserPicturesPlugin/temp2/trac-UserPicturesPlugin-master$python setup.py sdist
running sdist
running egg_info
writing trac_UserPicturesPlugin.egg-info/PKG-INFO
writing top-level names to trac_UserPicturesPlugin.egg-info/top_level.txt
writing dependency_links to trac_UserPicturesPlugin.egg-info/dependency_links.txt
writing entry points to trac_UserPicturesPlugin.egg-info/entry_points.txt
reading manifest file 'trac_UserPicturesPlugin.egg-info/SOURCES.txt'
writing manifest file 'trac_UserPicturesPlugin.egg-info/SOURCES.txt'
running check
creating trac-UserPicturesPlugin-0.1.1
creating trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
creating trac-UserPicturesPlugin-0.1.1/userpictures
creating trac-UserPicturesPlugin-0.1.1/userpictures/htdocs
creating trac-UserPicturesPlugin-0.1.1/userpictures/providers
making hard links in trac-UserPicturesPlugin-0.1.1...
hard linking README.txt -> trac-UserPicturesPlugin-0.1.1
hard linking setup.py -> trac-UserPicturesPlugin-0.1.1
hard linking trac_UserPicturesPlugin.egg-info/PKG-INFO -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/SOURCES.txt -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/dependency_links.txt -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/entry_points.txt -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/not-zip-safe -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking trac_UserPicturesPlugin.egg-info/top_level.txt -> trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info
hard linking userpictures/__init__.py -> trac-UserPicturesPlugin-0.1.1/userpictures
hard linking userpictures/htdocs/default-portrait.gif -> trac-UserPicturesPlugin-0.1.1/userpictures/htdocs
hard linking userpictures/htdocs/userpictures.css -> trac-UserPicturesPlugin-0.1.1/userpictures/htdocs
hard linking userpictures/providers/__init__.py -> trac-UserPicturesPlugin-0.1.1/userpictures/providers
hard linking userpictures/providers/gravatar.py -> trac-UserPicturesPlugin-0.1.1/userpictures/providers
hard linking userpictures/providers/usermanager.py -> trac-UserPicturesPlugin-0.1.1/userpictures/providers
Writing trac-UserPicturesPlugin-0.1.1/setup.cfg
Creating tar archive
removing 'trac-UserPicturesPlugin-0.1.1' (and everything under it)
(pve)~/Documents/Workspace/th-dev/UserPicturesPlugin/temp2/trac-UserPicturesPlugin-master$tar tzvf dist/trac-UserPicturesPlugin-0.1.1.tar.gz 
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/
-rw-r--r--  0 rjollos staff    3682 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/PKG-INFO
-rw-r--r--  0 rjollos staff    2588 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/README.txt
-rw-r--r--  0 rjollos staff      59 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/setup.cfg
-rw-r--r--  0 rjollos staff     817 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/setup.py
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/
-rw-r--r--  0 rjollos staff       1 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/dependency_links.txt
-rw-r--r--  0 rjollos staff      62 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/entry_points.txt
-rw-r--r--  0 rjollos staff       1 Jan  1 20:26 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/not-zip-safe
-rw-r--r--  0 rjollos staff    3682 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/PKG-INFO
-rw-r--r--  0 rjollos staff     514 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/SOURCES.txt
-rw-r--r--  0 rjollos staff      13 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/trac_UserPicturesPlugin.egg-info/top_level.txt
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/userpictures/
-rw-r--r--  0 rjollos staff   14170 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/__init__.py
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/userpictures/htdocs/
-rw-r--r--  0 rjollos staff    1104 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/htdocs/default-portrait.gif
-rw-r--r--  0 rjollos staff    1244 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/htdocs/userpictures.css
drwxr-xr-x  0 rjollos staff       0 Jan  1 20:27 trac-UserPicturesPlugin-0.1.1/userpictures/providers/
-rw-r--r--  0 rjollos staff     157 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/providers/__init__.py
-rw-r--r--  0 rjollos staff    1441 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/providers/gravatar.py
-rw-r--r--  0 rjollos staff     834 Aug 20  2012 trac-UserPicturesPlugin-0.1.1/userpictures/providers/usermanager.py
```

**Comment by rjollos** [comment]
#2 has been merged, so this issue could be closed.

**Comment by rjollos** [comment]
Note also, the [mirror on BitBucket](https://bitbucket.org/boldprogressives/trac-userpictures-plugin/commits/all) still has this issue.

**Comment by aensley** [comment]
Works for me!
